/**
 * Built-in copy of the tour and destination catalogue.
 * GENERATED by data/build_catalog.py from data/*.json. Do not edit by hand.
 */
import { Tour } from '../services/tour.service';
import { Destination } from '../services/destination.service';

export const ROUND_TOURS: Tour[] = [
  {
    "id": "tour-grand-island-odyssey",
    "title": "The Grand Island Odyssey",
    "duration": "14 Days / 13 Nights",
    "targetAudience": "First-time travelers seeking a comprehensive, leisurely luxury loop",
    "route": "Negombo → Cultural Triangle → Kandy → Hatton / Nuwara Eliya → Ella → Yala → Galle Fort → Colombo",
    "category": "14",
    "type": "round",
    "badge": {
      "text": "Signature 14-Day Tour",
      "class": "bg-gold"
    },
    "image": "images/tours/tour-grand-odyssey.jpg",
    "priceType": "Signature Luxury",
    "priceDisplay": "Price on Request",
    "priceTypeFull": "Signature Grand Tour",
    "priceDisplayFull": "• Bespoke Luxury Quotation",
    "featured": true,
    "market": "uk",
    "highlights": [
      "Sunrise ascent of the Sigiriya Lion Rock fortress before peak midday heat",
      "Exploration of the Polonnaruwa medieval ruins by bicycle or private buggy",
      "Chanted evening Theva puja service at the Temple of the Sacred Tooth Relic in Kandy",
      "The scenic hill country mainline train ride through working tea plantations",
      "Two private leopard and elephant game drives in Yala National Park with an experienced naturalist",
      "Leisurely walking tour across the 17th-century ramparts of UNESCO-listed Galle Fort"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival & Coastal Decompression",
        "location": "Negombo",
        "description": "Arrival at Bandaranaike International Airport (CMB). Meet private chauffeur-guide; short 25-minute transfer to a coastal boutique retreat in Negombo. Rest and unwind by the Indian Ocean."
      },
      {
        "day": "Day 2",
        "title": "Coastal Wetlands to the Cultural Triangle",
        "location": "Dambulla & Sigiriya",
        "description": "Drive inland toward the Cultural Triangle (approx. 4 hours). Stop en route at the Dambulla Cave Temple complex to explore the five sacred rock-cut sanctuaries filled with ancient Buddhist mural art. Check in to a tranquil jungle retreat."
      },
      {
        "day": "Day 3",
        "title": "The Sky Citadel & Rural Heritage",
        "location": "Sigiriya & Minneriya",
        "description": "Early morning ascent of Sigiriya Rock Fortress (5th-century palace citadel) to beat heat and crowds. Afternoon 4x4 open-top jeep safari in Minneriya/Kaudulla National Park to witness the seasonal gathering of wild elephant herds."
      },
      {
        "day": "Day 4",
        "title": "Ancient Kings & Royal Reservoirs",
        "location": "Polonnaruwa",
        "description": "Visit the ancient capital of Polonnaruwa, cycling among monumental stone stupas and the Gal Vihara rock reliefs. Traditional lakeside lunch prepared in clay pots at a local farming village."
      },
      {
        "day": "Day 5",
        "title": "Sacred Peaks to the Royal Capital",
        "location": "Kandy",
        "description": "Scenic transfer south to Kandy (approx. 2.5 hours) with an aromatic walk through an ethical spice estate in Matale. Experience the rhythmic drums and traditional evening prayer ceremony at Sri Dalada Maligawa (Temple of the Sacred Tooth Relic)."
      },
      {
        "day": "Day 6",
        "title": "Botanical Splendor & Crafts",
        "location": "Kandy",
        "description": "Guided stroll across the Royal Botanic Gardens, Peradeniya, home to an extensive orchid collection and royal palm avenues. Scenic lake drive, gemstone museum visit, and an evening cultural drum and dance performance."
      },
      {
        "day": "Day 7",
        "title": "The Emerald Tea Valleys",
        "location": "Hatton / Nuwara Eliya",
        "description": "Drive through winding highlands lined with cascading waterfalls (approx. 2.5–3 hours). Private tour of a working orthodox tea factory; masterclass on tea plucking, rolling, drying, and an estate-grade tea tasting."
      },
      {
        "day": "Day 8",
        "title": "High Plains & Panorama",
        "location": "Horton Plains & Nuwara Eliya",
        "description": "Dawn excursion to Horton Plains National Park; trek to the 1,200m drop at World's End and Baker's Falls. Explore 'Little England,' visiting Victoria Park, the colonial Queen's Hotel, and Gregory Lake."
      },
      {
        "day": "Day 9",
        "title": "The Mainline Scenic Rail to Ella",
        "location": "Ella",
        "description": "Board the morning observation-class scenic train from Nanu Oya to Ella through tea plantations and cloud forests. Walk along the tracks to the Nine Arches Bridge to photograph passing trains; easy hike to Little Adam's Peak for sunset."
      },
      {
        "day": "Day 10",
        "title": "Down into the Southern Wilds",
        "location": "Yala National Park",
        "description": "Descend the southern mountain escarpment via Ravana Falls toward the arid southern coastal plain (approx. 3 hours). First private open-top 4x4 evening safari in Yala National Park scouting for leopards, sloth bears, and mugger crocodiles."
      },
      {
        "day": "Day 11",
        "title": "Dawn Safari & Southern Coastline",
        "location": "Galle Fort",
        "description": "Early-morning second game drive in Yala Block 1. Return for late brunch. Drive west along the southern coastline past Weligama to the Dutch colonial fortress of Galle (approx. 2.5 hours)."
      },
      {
        "day": "Day 12",
        "title": "Colonial Bastions & Artisan Alleys",
        "location": "Galle Fort",
        "description": "Private architecture and history walking tour within the fortified walls of Galle Fort, exploring cobblestone streets, antique stores, and historic bastions. Free afternoon to relax at nearby Thalpe beach or enjoy an Ayurvedic treatment."
      },
      {
        "day": "Day 13",
        "title": "Ocean Sunsets & Stilt Fishermen",
        "location": "Southern Coast & Bentota",
        "description": "Dedicated slow-travel day. Options to visit a sea turtle conservation hatchery in Kosgoda, take an estuary river boat cruise on the Madu Ganga, or relax along the beach."
      },
      {
        "day": "Day 14",
        "title": "Departure & Farewell",
        "location": "Colombo Airport",
        "description": "Transfer directly via the Southern Expressway (approx. 2 hours) to Bandaranaike International Airport (CMB) for outward flight."
      }
    ],
    "inclusions": [
      "Private air-conditioned luxury vehicle with an English-speaking Chauffeur-Guide",
      "All entrance fees and permits for listed heritage sites and national parks",
      "Private 4x4 safari jeeps with park tracker/naturalist",
      "First-class reserved observation rail tickets (subject to availability)",
      "Daily breakfast and designated gourmet meal experiences",
      "Highway toll charges, fuel, chauffeur accommodation and meals",
      "24/7 dedicated local concierge support"
    ],
    "exclusions": [
      "International flights and Sri Lanka ETA tourist visa fees",
      "Discretionary driver/guide gratuities",
      "Travel insurance (mandatory for booking)",
      "Alcoholic beverages and personal expenses"
    ],
    "bestTime": "December – April",
    "isActive": true
  },
  {
    "id": "tour-wild-heritage-highlands",
    "title": "Wild Heritage & Highlands",
    "duration": "10 Days / 9 Nights",
    "targetAudience": "Wildlife enthusiasts, active couples, and photography buffs",
    "route": "Negombo → Wilpattu National Park → Sigiriya → Kandy → Ella → Yala → Southern Beach",
    "category": "10",
    "type": "round",
    "badge": {
      "text": "Wildlife & Adventure",
      "class": "bg-teal"
    },
    "image": "images/tours/tour-cultural-triangle.jpg",
    "priceType": "Curated Private Tour",
    "priceDisplay": "Price on Request",
    "priceTypeFull": "Curated Wildlife Safari",
    "priceDisplayFull": "• Bespoke Luxury Quotation",
    "featured": true,
    "market": "uk",
    "highlights": [
      "Remote leopard tracking in Wilpattu's undisturbed natural lake basins (Villus)",
      "Sunset hike up Pidurangala Rock with panoramic views facing Sigiriya",
      "Guided wildlife and bird-watching expeditions in two distinct national parks",
      "Classic colonial rail passage through misty highland passes",
      "Coastal relaxation on the golden beaches of Mirissa"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival in Sri Lanka",
        "location": "Negombo",
        "description": "Arrival at CMB Airport; short transfer to Negombo boutique hotel for rest and ocean decompression."
      },
      {
        "day": "Day 2",
        "title": "Untamed Wilpattu Safari",
        "location": "Wilpattu National Park",
        "description": "Negombo to Wilpattu National Park; afternoon 4x4 wilderness safari tracking wild sloth bears and leopards around natural lakes."
      },
      {
        "day": "Day 3",
        "title": "Kingdom of Sigiriya & Pidurangala",
        "location": "Sigiriya",
        "description": "Wilpattu to Sigiriya; evening sunset climb atop Pidurangala Rock with 360-degree panoramic views of Lion Rock."
      },
      {
        "day": "Day 4",
        "title": "Sky Citadel & Elephant Corridors",
        "location": "Sigiriya & Minneriya",
        "description": "Sunrise climb of Sigiriya Fortress; afternoon exploration of rural ancient irrigation tanks and Minneriya elephant corridors."
      },
      {
        "day": "Day 5",
        "title": "Sacred Golden Caves & Hill Capital",
        "location": "Dambulla & Kandy",
        "description": "Dambulla Cave Temple en route to Kandy; evening visit to the sacred Temple of the Tooth Relic."
      },
      {
        "day": "Day 6",
        "title": "Misty Highland Rail to Ella",
        "location": "Ella",
        "description": "The scenic hill-country train from Kandy to Ella (about 6–7 hours) through tea estates and cloud forest. A quiet evening in Ella after a long, beautiful day."
      },
      {
        "day": "Day 7",
        "title": "Escarpment Descent to Yala",
        "location": "Yala National Park",
        "description": "Morning walk up Little Adam's Peak and a stop at the Nine Arches Bridge, then descend the escarpment past Ravana Falls to Yala for an afternoon leopard safari."
      },
      {
        "day": "Day 8",
        "title": "Dawn Game Drive & Ocean Coast",
        "location": "Yala & Mirissa",
        "description": "Dawn safari in Yala National Park Block 1; transfer along the southern coast past Weligama to Mirissa."
      },
      {
        "day": "Day 9",
        "title": "Whale Watching & Golden Shores",
        "location": "Mirissa",
        "description": "Whale-watching excursion (seasonal: Nov–April) or relaxed day on Mirissa beach with fresh seafood dining."
      },
      {
        "day": "Day 10",
        "title": "Galle Fort & Airport Departure",
        "location": "Galle & CMB Airport",
        "description": "Scenic drive past Galle Fort ramparts, then express transfer via Southern Expressway to CMB Airport for departure."
      }
    ],
    "inclusions": [
      "Private air-conditioned luxury vehicle with an English-speaking Chauffeur-Guide",
      "All entrance fees and permits for listed heritage sites and national parks",
      "Private 4x4 safari jeeps with park tracker/naturalist",
      "First-class reserved observation rail tickets (subject to availability)",
      "Daily breakfast and designated gourmet meal experiences",
      "Highway toll charges, fuel, chauffeur accommodation and meals",
      "24/7 dedicated local concierge support"
    ],
    "exclusions": [
      "International flights and Sri Lanka ETA tourist visa fees",
      "Discretionary driver/guide gratuities",
      "Travel insurance (mandatory for booking)",
      "Alcoholic beverages and personal expenses"
    ],
    "bestTime": "February – April",
    "isActive": true
  },
  {
    "id": "tour-tea-trails-coastal-sanctuaries",
    "title": "Tea Trails & Coastal Sanctuaries",
    "duration": "8 Days / 7 Nights",
    "targetAudience": "Travelers seeking romance, boutique relaxation, and slow travel",
    "route": "Colombo → Tea Country (Hatton/Castlereagh) → Galle Fort → Bentota → Airport",
    "category": "8",
    "type": "round",
    "badge": {
      "text": "Boutique & Romance",
      "class": "bg-charcoal"
    },
    "image": "images/tours/day-tour-tea.jpg",
    "priceType": "Luxury Boutique",
    "priceDisplay": "Price on Request",
    "priceTypeFull": "Boutique Tea & Coastal Haven",
    "priceDisplayFull": "• Bespoke Luxury Quotation",
    "featured": true,
    "market": "uk",
    "highlights": [
      "Stay in heritage tea bungalows amidst rolling hills and private lakeside estates",
      "Artisan culinary walks through Galle Fort paired with fine dining",
      "Private ocean catamaran sailings and golden sand beaches",
      "Gentle pace with limited drive times and maximum relaxation"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Colombo Heritage & Sunset Cocktails",
        "location": "Colombo",
        "description": "Arrival in Colombo; evening architectural tour of colonial Fort and vintage sunset cocktails at Galle Face Hotel."
      },
      {
        "day": "Day 2",
        "title": "Ascent to Tea Country Estates",
        "location": "Hatton / Castlereagh",
        "description": "Transfer to Hatton / Castlereagh Reservoir (approx. 4.5 hours); check into a restored heritage tea planter's bungalow."
      },
      {
        "day": "Day 3",
        "title": "Tea Masterclass & Lake Panoramas",
        "location": "Castlereagh Reservoir",
        "description": "Private garden tea-tasting experience, gentle estate walking trails, and afternoon cream tea overlooking the misty lake."
      },
      {
        "day": "Day 4",
        "title": "Descent to the Colonial Coast",
        "location": "Galle Fort",
        "description": "Descend through rubber plantations and winding rivers directly toward the southern coast to Galle (approx. 4 hours)."
      },
      {
        "day": "Day 5",
        "title": "Galle Fort Historic Walk",
        "location": "Galle Fort",
        "description": "Walking tour of UNESCO Galle Fort with an architectural historian; sunset drinks on the lighthouse wall."
      },
      {
        "day": "Day 6",
        "title": "Tropical Modernism at Lunuganga",
        "location": "Bentota",
        "description": "Transfer to Bentota; visit Geoffrey Bawa's legendary tropical modernist country estate, Lunuganga."
      },
      {
        "day": "Day 7",
        "title": "Ayurveda Wellness & Candlelight Dining",
        "location": "Bentota Beach",
        "description": "Leisurely coastal day; private Ayurvedic wellness treatment, golden beach walk, and candlelight seafood dinner."
      },
      {
        "day": "Day 8",
        "title": "Express Highway Transfer to CMB",
        "location": "Colombo Airport",
        "description": "90-minute highway transfer directly to Bandaranaike International Airport (CMB) for departure flight."
      }
    ],
    "inclusions": [
      "Private air-conditioned luxury vehicle with an English-speaking Chauffeur-Guide",
      "All entrance fees and permits for listed heritage sites and national parks",
      "Private 4x4 safari jeeps with park tracker/naturalist",
      "First-class reserved observation rail tickets (subject to availability)",
      "Daily breakfast and designated gourmet meal experiences",
      "Highway toll charges, fuel, chauffeur accommodation and meals",
      "24/7 dedicated local concierge support"
    ],
    "exclusions": [
      "International flights and Sri Lanka ETA tourist visa fees",
      "Discretionary driver/guide gratuities",
      "Travel insurance (mandatory for booking)",
      "Alcoholic beverages and personal expenses"
    ],
    "bestTime": "December – April",
    "isActive": true
  },
  {
    "id": "tour-essence-of-ceylon",
    "title": "Essence of Ceylon",
    "duration": "7 Days / 6 Nights",
    "targetAudience": "Short-break travelers seeking the essential cultural highlights and southern sea",
    "route": "Airport → Sigiriya → Kandy → Galle → Airport",
    "category": "7",
    "type": "round",
    "badge": {
      "text": "Essential Sri Lanka",
      "class": "bg-teal"
    },
    "image": "images/tours/tour-southern-coast.jpg",
    "priceType": "Classic Private Tour",
    "priceDisplay": "Price on Request",
    "priceTypeFull": "Curated Essential Highlights",
    "priceDisplayFull": "• Bespoke Luxury Quotation",
    "featured": true,
    "market": "uk",
    "highlights": [
      "Direct access to the country's two most renowned UNESCO cultural monuments: Sigiriya and Kandy",
      "Dense, high-value 7-day loop without excessive packing and unpacking",
      "Coastal finale within the historic ramparts of Galle Fort"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival to the Ancient Triangle",
        "location": "Sigiriya",
        "description": "Arrive at CMB and continue north to the Cultural Triangle (about 4 hours) for an evening at a forest lodge. Best suited to morning arrivals; if your flight lands late, we add a first night in Negombo so you never face a long drive after a long flight."
      },
      {
        "day": "Day 2",
        "title": "Sigiriya Rock & Elephant Safari",
        "location": "Sigiriya & Minneriya",
        "description": "Early climb of Sigiriya Lion Rock; afternoon safari at Minneriya National Park for the wild elephant gathering."
      },
      {
        "day": "Day 3",
        "title": "Dambulla Murals & Temple of the Tooth",
        "location": "Kandy",
        "description": "Visit Dambulla Golden Rock Cave Temples, continuing south to Kandy; evening service at the Temple of the Sacred Tooth Relic."
      },
      {
        "day": "Day 4",
        "title": "Royal Gardens & Mountain Cascades",
        "location": "Kandy to Galle",
        "description": "Morning stroll through the Royal Botanic Gardens; scenic drive past highland cascades south toward Galle."
      },
      {
        "day": "Day 5",
        "title": "Exploring Colonial Galle Fort",
        "location": "Galle Fort",
        "description": "Full day discovering Galle Fort's artisanal boutiques, gem traders, ramparts, and historic Dutch Reformed Church."
      },
      {
        "day": "Day 6",
        "title": "Palm-Fringed Coastal Day",
        "location": "Thalpe / Unawatuna",
        "description": "Relaxing day on the palm-fringed beaches of Unawatuna or Thalpe; farewell oceanfront dining."
      },
      {
        "day": "Day 7",
        "title": "Express Highway Transfer",
        "location": "CMB Airport",
        "description": "Southern Expressway transfer directly to CMB Airport for return flight."
      }
    ],
    "inclusions": [
      "Private air-conditioned luxury vehicle with an English-speaking Chauffeur-Guide",
      "All entrance fees and permits for listed heritage sites and national parks",
      "Private 4x4 safari jeeps with park tracker/naturalist",
      "First-class reserved observation rail tickets (subject to availability)",
      "Daily breakfast and designated gourmet meal experiences",
      "Highway toll charges, fuel, chauffeur accommodation and meals",
      "24/7 dedicated local concierge support"
    ],
    "exclusions": [
      "International flights and Sri Lanka ETA tourist visa fees",
      "Discretionary driver/guide gratuities",
      "Travel insurance (mandatory for booking)",
      "Alcoholic beverages and personal expenses"
    ],
    "bestTime": "December – April",
    "isActive": true
  },
  {
    "id": "tour-east-coast-summer",
    "title": "East Coast Summer Escape",
    "duration": "10 Days / 9 Nights",
    "bestTime": "May – September",
    "targetAudience": "Summer holidays, when the east coast is at its best and the south-west sees the monsoon",
    "route": "Negombo → Sigiriya → Trincomalee → Pasikudah → Kandy",
    "category": "10",
    "type": "round",
    "featured": false,
    "market": "uk",
    "badge": {
      "text": "Summer Season",
      "class": "bg-teal"
    },
    "image": "images/tours/day-tour-whale.jpg",
    "priceType": "Tailor-made",
    "priceDisplay": "Price on Request",
    "highlights": [
      "Sigiriya at sunrise and the great elephant gathering at Minneriya or Kaudulla",
      "Snorkelling among reef sharks and turtles at Pigeon Island National Park",
      "Whale and dolphin watching off Trincomalee (seasonal, March to August)",
      "Calm, shallow turquoise water on the long beach at Pasikudah",
      "Evening ceremony at the Temple of the Sacred Tooth Relic in Kandy"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival & Rest by the Sea",
        "location": "Negombo",
        "description": "Meet your chauffeur-guide at Bandaranaike International Airport and take the short transfer to a beachside hotel in Negombo to rest after the flight.",
        "drive": "25 min · 12 km"
      },
      {
        "day": "Day 2",
        "title": "Into the Cultural Triangle",
        "location": "Sigiriya",
        "description": "Drive inland through coconut country to Sigiriya. Afternoon village walk with a traditional lunch cooked in a local home.",
        "drive": "4 hrs · 165 km"
      },
      {
        "day": "Day 3",
        "title": "Lion Rock & the Elephant Gathering",
        "location": "Sigiriya",
        "description": "Climb Sigiriya Rock early, before the heat. In the afternoon, a private jeep safari to Minneriya or Kaudulla, where hundreds of wild elephants gather at the reservoirs in the dry season."
      },
      {
        "day": "Day 4",
        "title": "To the Eastern Shore",
        "location": "Trincomalee",
        "description": "Continue east to Trincomalee. Sunset at Koneswaram Temple on Swami Rock, high above the ocean.",
        "drive": "2.5 hrs · 105 km"
      },
      {
        "day": "Day 5",
        "title": "Pigeon Island Reef",
        "location": "Trincomalee",
        "description": "Boat to Pigeon Island National Park for snorkelling over coral gardens with reef fish, turtles and black-tip reef sharks. Afternoon at leisure on Nilaveli beach."
      },
      {
        "day": "Day 6",
        "title": "Whales & Dolphins",
        "location": "Trincomalee",
        "description": "Early boat excursion to look for blue whales, sperm whales and spinner dolphins (best March to August). Afternoon free."
      },
      {
        "day": "Day 7",
        "title": "Pasikudah Bay",
        "location": "Pasikudah",
        "description": "Drive south along the coast to Pasikudah, a sheltered bay of shallow, warm water perfect for swimming.",
        "drive": "2.5 hrs · 110 km"
      },
      {
        "day": "Day 8",
        "title": "Beach Day",
        "location": "Pasikudah",
        "description": "A free day by the sea. Optional: kayaking in the lagoon or a visit to the fishing village at dawn."
      },
      {
        "day": "Day 9",
        "title": "Up to the Hill Capital",
        "location": "Kandy",
        "description": "Cross the island to Kandy. Evening ceremony at the Temple of the Sacred Tooth Relic.",
        "drive": "4.5 hrs · 190 km"
      },
      {
        "day": "Day 10",
        "title": "Departure",
        "location": "Airport",
        "description": "Morning at the Royal Botanic Gardens, Peradeniya (time permitting), then transfer to the airport for your flight home.",
        "drive": "3.5 hrs · 110 km"
      }
    ],
    "inclusions": [
      "Private air-conditioned vehicle with an English-speaking chauffeur-guide",
      "Accommodation as listed (or similar) with daily breakfast",
      "Entrance fees for the sites and safaris named in the itinerary",
      "Highway tolls, fuel, and your chauffeur-guide's accommodation and meals",
      "Bottled water in the vehicle",
      "24/7 local support throughout your journey",
      "Pigeon Island boat and snorkelling equipment",
      "Shared whale-watching boat"
    ],
    "exclusions": [
      "International flights and Sri Lanka visa / ETA fees",
      "Travel insurance (required for every booking)",
      "Meals not stated, drinks and personal expenses",
      "Gratuities for guides, drivers and hotel staff"
    ],
    "isActive": true
  },
  {
    "id": "tour-ayurveda-wellness",
    "title": "Ayurveda & Wellness Retreat",
    "duration": "10 Days / 9 Nights",
    "bestTime": "November – April",
    "targetAudience": "Travellers who want to slow down, restore and travel lightly",
    "route": "Airport → Ayurveda retreat (west coast) → Galle Fort → Airport",
    "category": "10",
    "type": "round",
    "featured": false,
    "market": "uk",
    "badge": {
      "text": "Wellness",
      "class": "bg-charcoal"
    },
    "image": "images/destinations/mirissa.jpg",
    "priceType": "Tailor-made",
    "priceDisplay": "Price on Request",
    "highlights": [
      "A personal consultation with a qualified Ayurvedic doctor",
      "Daily treatments tailored to you, with yoga and meditation",
      "Ayurvedic cookery: learn to cook with healing spices",
      "A quiet day at Geoffrey Bawa's garden at Lunuganga",
      "Two unhurried nights inside the walls of Galle Fort"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival & Consultation",
        "location": "West coast retreat",
        "description": "Transfer to a dedicated Ayurveda retreat on the west coast. In the afternoon, an unhurried consultation with the resident Ayurvedic doctor, who plans your treatments and diet.",
        "drive": "1.5–2 hrs · 100 km"
      },
      {
        "day": "Day 2",
        "title": "Settling In",
        "location": "West coast retreat",
        "description": "Morning yoga, then your first full day of treatments. Herbal baths, oil therapies and rest."
      },
      {
        "day": "Day 3",
        "title": "Treatments & Rest",
        "location": "West coast retreat",
        "description": "A daily rhythm of yoga, treatments, healthy meals and time by the sea."
      },
      {
        "day": "Day 4",
        "title": "Ayurvedic Cookery",
        "location": "West coast retreat",
        "description": "Join the retreat chef to learn how Ayurvedic cooking uses spices to balance body and mind."
      },
      {
        "day": "Day 5",
        "title": "Lunuganga Gardens",
        "location": "West coast retreat",
        "description": "A gentle half-day outing to Lunuganga, the country garden of architect Geoffrey Bawa, then back for afternoon treatments."
      },
      {
        "day": "Day 6",
        "title": "Treatments & Rest",
        "location": "West coast retreat",
        "description": "Continue your programme. Optional river boat trip on the Madu Ganga mangroves."
      },
      {
        "day": "Day 7",
        "title": "Final Retreat Day",
        "location": "West coast retreat",
        "description": "A closing consultation, with advice to take home."
      },
      {
        "day": "Day 8",
        "title": "To Galle Fort",
        "location": "Galle",
        "description": "A short drive south to a boutique hotel inside UNESCO-listed Galle Fort.",
        "drive": "1.5 hrs · 70 km"
      },
      {
        "day": "Day 9",
        "title": "Galle at Your Pace",
        "location": "Galle",
        "description": "Walk the ramparts at sunrise, browse the galleries and cafés, and end with sunset on the lighthouse wall."
      },
      {
        "day": "Day 10",
        "title": "Departure",
        "location": "Airport",
        "description": "Transfer to the airport via the Southern Expressway.",
        "drive": "2.5 hrs · 150 km"
      }
    ],
    "inclusions": [
      "Private air-conditioned vehicle with an English-speaking chauffeur-guide",
      "Full-board Ayurveda programme at the retreat, with daily treatments as prescribed",
      "Doctor consultations, yoga and meditation sessions",
      "Bed and breakfast in Galle",
      "Highway tolls, fuel, and your chauffeur-guide's accommodation and meals",
      "Bottled water in the vehicle",
      "24/7 local support throughout your journey"
    ],
    "exclusions": [
      "International flights and Sri Lanka visa / ETA fees",
      "Travel insurance (required for every booking)",
      "Meals not stated, drinks and personal expenses",
      "Gratuities for guides, drivers and hotel staff"
    ],
    "isActive": true
  },
  {
    "id": "tour-spice-tea-table",
    "title": "Spice, Tea & Table",
    "duration": "9 Days / 8 Nights",
    "bestTime": "December – April",
    "targetAudience": "Food lovers who would rather cook with locals than just eat out",
    "route": "Colombo → Kandy → Tea Country → Galle Fort",
    "category": "8",
    "type": "round",
    "featured": false,
    "market": "uk",
    "badge": {
      "text": "Food & Culture",
      "class": "bg-gold"
    },
    "image": "images/destinations/nuwara-eliya.jpg",
    "priceType": "Tailor-made",
    "priceDisplay": "Price on Request",
    "highlights": [
      "An evening street-food walk in Colombo",
      "Hands-on cookery in a family kitchen near Kandy, not just a demonstration",
      "A spice garden visit in Matale with the people who grow them",
      "Tea plucking, a factory tour and a private tasting in the hill country",
      "Morning at Galle's fish market, then cooking your catch with a chef"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival & Street Food",
        "location": "Colombo",
        "description": "Transfer to Colombo. In the evening, a guided street-food walk: kottu, hoppers and short eats around Galle Face Green.",
        "drive": "45 min · 35 km"
      },
      {
        "day": "Day 2",
        "title": "To the Hill Capital",
        "location": "Kandy",
        "description": "Drive to Kandy with lunch at a local rice-and-curry house on the way. Evening at the Temple of the Sacred Tooth Relic.",
        "drive": "3.5 hrs · 115 km"
      },
      {
        "day": "Day 3",
        "title": "Spice Garden & Family Kitchen",
        "location": "Kandy",
        "description": "Visit a spice garden in Matale, then cook a full rice-and-curry lunch with a local family in their kitchen."
      },
      {
        "day": "Day 4",
        "title": "Into Tea Country",
        "location": "Hill country",
        "description": "Climb into the hills past waterfalls to a heritage tea bungalow.",
        "drive": "3 hrs · 80 km"
      },
      {
        "day": "Day 5",
        "title": "From Leaf to Cup",
        "location": "Hill country",
        "description": "Join the tea pluckers in the morning, follow the leaf through a working factory, then a private tasting. Planter's dinner at the bungalow."
      },
      {
        "day": "Day 6",
        "title": "Down to the Coast",
        "location": "Galle",
        "description": "A long but beautiful drive from the hills to Galle Fort on the south coast.",
        "drive": "5 hrs · 230 km"
      },
      {
        "day": "Day 7",
        "title": "Market to Kitchen",
        "location": "Galle",
        "description": "Early visit to the fish market with a chef, then cook your catch together."
      },
      {
        "day": "Day 8",
        "title": "Galle Fort Food Walk",
        "location": "Galle",
        "description": "A tasting walk through the fort's cafés and kitchens. Farewell dinner."
      },
      {
        "day": "Day 9",
        "title": "Departure",
        "location": "Airport",
        "description": "Transfer to the airport via the Southern Expressway.",
        "drive": "2.5 hrs · 150 km"
      }
    ],
    "inclusions": [
      "Private air-conditioned vehicle with an English-speaking chauffeur-guide",
      "Accommodation as listed (or similar) with daily breakfast",
      "Entrance fees for the sites and safaris named in the itinerary",
      "Highway tolls, fuel, and your chauffeur-guide's accommodation and meals",
      "Bottled water in the vehicle",
      "24/7 local support throughout your journey",
      "Street-food walk, two cookery classes and a private tea tasting"
    ],
    "exclusions": [
      "International flights and Sri Lanka visa / ETA fees",
      "Travel insurance (required for every booking)",
      "Meals not stated, drinks and personal expenses",
      "Gratuities for guides, drivers and hotel staff"
    ],
    "isActive": true
  },
  {
    "id": "tour-honeymoon-romance",
    "title": "Romance in Ceylon",
    "duration": "11 Days / 10 Nights",
    "bestTime": "December – April",
    "targetAudience": "Honeymooners and couples celebrating something special",
    "route": "Negombo → Sigiriya → Kandy → Tea Country → Ella → South Coast",
    "category": "10",
    "type": "round",
    "featured": false,
    "market": "uk",
    "badge": {
      "text": "Honeymoon",
      "class": "bg-gold"
    },
    "image": "images/tours/day-tour-galle.jpg",
    "priceType": "Tailor-made",
    "priceDisplay": "Price on Request",
    "highlights": [
      "Private sunrise climb of Sigiriya and an optional hot-air balloon flight",
      "A candlelit dinner in a colonial tea planter's bungalow",
      "The famous hill-country train ride to Ella, in reserved seats",
      "Four nights in a private beach villa on the south coast",
      "Romantic touches arranged throughout, from flowers to surprise dinners"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival",
        "location": "Negombo",
        "description": "A gentle start by the sea after your flight.",
        "drive": "25 min · 12 km"
      },
      {
        "day": "Day 2",
        "title": "To Sigiriya",
        "location": "Sigiriya",
        "description": "Drive to a secluded jungle lodge near Sigiriya. Sunset from Pidurangala Rock.",
        "drive": "4 hrs · 165 km"
      },
      {
        "day": "Day 3",
        "title": "Lion Rock & Balloons",
        "location": "Sigiriya",
        "description": "Optional dawn hot-air balloon flight (weather permitting), then climb Sigiriya Rock. Afternoon spa time."
      },
      {
        "day": "Day 4",
        "title": "Dambulla & Kandy",
        "location": "Kandy",
        "description": "The painted cave temples of Dambulla, then on to Kandy for the evening temple ceremony.",
        "drive": "2.5 hrs · 90 km"
      },
      {
        "day": "Day 5",
        "title": "Into the Tea Hills",
        "location": "Hill country",
        "description": "Through the tea estates to a colonial bungalow. Candlelit dinner for two.",
        "drive": "3 hrs · 80 km"
      },
      {
        "day": "Day 6",
        "title": "Tea Country at Leisure",
        "location": "Hill country",
        "description": "A private tea tasting and an easy estate walk, or simply time together on the veranda."
      },
      {
        "day": "Day 7",
        "title": "The Train to Ella & Down to the Sea",
        "location": "South coast",
        "description": "Board the train from Nanu Oya to Ella through the clouds, then drive down to your beach villa.",
        "drive": "Train 3 hrs + drive 3 hrs"
      },
      {
        "day": "Day 8",
        "title": "Beach Villa",
        "location": "South coast",
        "description": "Days of your own making: swimming, spa, and long lunches by the sea."
      },
      {
        "day": "Day 9",
        "title": "Whales or Slow Morning",
        "location": "South coast",
        "description": "Optional whale watching from Mirissa (November to April), or a quiet morning."
      },
      {
        "day": "Day 10",
        "title": "Galle Fort",
        "location": "South coast",
        "description": "An afternoon in Galle Fort and sunset on the ramparts. Private farewell dinner on the beach."
      },
      {
        "day": "Day 11",
        "title": "Departure",
        "location": "Airport",
        "description": "Transfer to the airport via the Southern Expressway.",
        "drive": "3 hrs · 190 km"
      }
    ],
    "inclusions": [
      "Private air-conditioned vehicle with an English-speaking chauffeur-guide",
      "Accommodation as listed (or similar) with daily breakfast",
      "Entrance fees for the sites and safaris named in the itinerary",
      "Highway tolls, fuel, and your chauffeur-guide's accommodation and meals",
      "Bottled water in the vehicle",
      "24/7 local support throughout your journey",
      "Reserved train seats (subject to availability)",
      "Romantic dinners as described"
    ],
    "exclusions": [
      "International flights and Sri Lanka visa / ETA fees",
      "Travel insurance (required for every booking)",
      "Meals not stated, drinks and personal expenses",
      "Gratuities for guides, drivers and hotel staff",
      "Hot-air balloon flight (optional, payable locally)"
    ],
    "isActive": true
  },
  {
    "id": "tour-family-adventure",
    "title": "Family Adventure",
    "duration": "10 Days / 9 Nights",
    "bestTime": "December – April, or July – August with an east-coast finish",
    "targetAudience": "Families with children aged 6 and up",
    "route": "Negombo → Sigiriya → Kandy → Ella → Udawalawe → South Coast",
    "category": "10",
    "type": "round",
    "featured": false,
    "market": "uk",
    "badge": {
      "text": "Family",
      "class": "bg-teal"
    },
    "image": "images/tours/day-tour-yala.jpg",
    "priceType": "Tailor-made",
    "priceDisplay": "Price on Request",
    "highlights": [
      "A village day with a bullock-cart ride, catamaran and home-cooked lunch",
      "A pottery session made for children",
      "The blue train to Ella and an easy hike up Little Adam's Peak",
      "Jeep safari in Udawalawe, home to large herds of wild elephants",
      "Visit to the Elephant Transit Home, which rescues and releases orphaned calves"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival",
        "location": "Negombo",
        "description": "A short transfer and an easy afternoon by the pool.",
        "drive": "25 min · 12 km"
      },
      {
        "day": "Day 2",
        "title": "Village Life",
        "location": "Sigiriya",
        "description": "Drive to Sigiriya. Afternoon village tour: bullock cart, catamaran across the lake and lunch in a local home.",
        "drive": "4 hrs · 165 km"
      },
      {
        "day": "Day 3",
        "title": "Lion Rock & Pottery",
        "location": "Sigiriya",
        "description": "Climb Sigiriya early. Afternoon pottery session for the children with a local potter."
      },
      {
        "day": "Day 4",
        "title": "Kandy",
        "location": "Kandy",
        "description": "Drive to Kandy. Evening cultural dance show and the Temple of the Tooth.",
        "drive": "2.5 hrs · 90 km"
      },
      {
        "day": "Day 5",
        "title": "The Blue Train",
        "location": "Ella",
        "description": "Take the scenic train into the hills, arriving in Ella.",
        "drive": "Train 6–7 hrs"
      },
      {
        "day": "Day 6",
        "title": "Ella Adventures",
        "location": "Ella",
        "description": "Easy morning hike up Little Adam's Peak, then the Nine Arches Bridge to watch a train cross."
      },
      {
        "day": "Day 7",
        "title": "Elephants!",
        "location": "Udawalawe",
        "description": "Drive down to Udawalawe. Afternoon jeep safari among the elephant herds.",
        "drive": "2.5 hrs · 110 km"
      },
      {
        "day": "Day 8",
        "title": "Elephant Transit Home & the Sea",
        "location": "South coast",
        "description": "Watch feeding time at the Elephant Transit Home, then on to the beach.",
        "drive": "2.5 hrs · 100 km"
      },
      {
        "day": "Day 9",
        "title": "Beach Day",
        "location": "South coast",
        "description": "Sandcastles, rock pools and a visit to a sea-turtle conservation project."
      },
      {
        "day": "Day 10",
        "title": "Departure",
        "location": "Airport",
        "description": "Transfer to the airport via the Southern Expressway.",
        "drive": "3 hrs · 180 km"
      }
    ],
    "inclusions": [
      "Private air-conditioned vehicle with an English-speaking chauffeur-guide",
      "Accommodation as listed (or similar) with daily breakfast",
      "Entrance fees for the sites and safaris named in the itinerary",
      "Highway tolls, fuel, and your chauffeur-guide's accommodation and meals",
      "Bottled water in the vehicle",
      "24/7 local support throughout your journey",
      "Family rooms or interconnecting rooms where available",
      "Village tour, pottery session and safari"
    ],
    "exclusions": [
      "International flights and Sri Lanka visa / ETA fees",
      "Travel insurance (required for every booking)",
      "Meals not stated, drinks and personal expenses",
      "Gratuities for guides, drivers and hotel staff"
    ],
    "isActive": true
  },
  {
    "id": "tour-wildlife-specialist",
    "title": "Leopards, Elephants & Whales",
    "duration": "11 Days / 10 Nights",
    "bestTime": "February – April",
    "targetAudience": "Wildlife enthusiasts and photographers",
    "route": "Negombo → Wilpattu → Habarana → Udawalawe → Yala → Mirissa",
    "category": "10",
    "type": "round",
    "featured": false,
    "market": "uk",
    "badge": {
      "text": "Wildlife",
      "class": "bg-teal"
    },
    "image": "images/destinations/yala.jpg",
    "priceType": "Tailor-made",
    "priceDisplay": "Price on Request",
    "highlights": [
      "Leopards and sloth bears in Wilpattu, Sri Lanka's largest national park",
      "The elephant gathering at Minneriya or Kaudulla",
      "Full-day safaris in Yala with an experienced naturalist",
      "Blue whales off Mirissa (November to April)",
      "Small-group or private jeeps throughout, timed for the best light"
    ],
    "itinerary": [
      {
        "day": "Day 1",
        "title": "Arrival",
        "location": "Negombo",
        "description": "Rest after the flight; evening birding in the Muthurajawela marshes (optional).",
        "drive": "25 min · 12 km"
      },
      {
        "day": "Day 2",
        "title": "To Wilpattu",
        "location": "Wilpattu",
        "description": "Drive north to a tented camp on the edge of Wilpattu. Afternoon safari.",
        "drive": "3.5 hrs · 150 km"
      },
      {
        "day": "Day 3",
        "title": "Wilpattu",
        "location": "Wilpattu",
        "description": "Full day in the park among its natural lakes, looking for leopard and sloth bear."
      },
      {
        "day": "Day 4",
        "title": "To Habarana",
        "location": "Habarana",
        "description": "Drive east to Habarana. Afternoon safari to Minneriya or Kaudulla for the elephant gathering.",
        "drive": "3 hrs · 140 km"
      },
      {
        "day": "Day 5",
        "title": "Sigiriya & Birding",
        "location": "Habarana",
        "description": "Sunrise climb of Sigiriya, then a guided birding walk in the scrub forest."
      },
      {
        "day": "Day 6",
        "title": "To Udawalawe",
        "location": "Udawalawe",
        "description": "A long transfer south. Late-afternoon safari among the elephant herds.",
        "drive": "5 hrs · 230 km"
      },
      {
        "day": "Day 7",
        "title": "To Yala",
        "location": "Yala",
        "description": "Morning at the Elephant Transit Home, then on to Yala for an afternoon game drive.",
        "drive": "2.5 hrs · 110 km"
      },
      {
        "day": "Day 8",
        "title": "Yala Full Day",
        "location": "Yala",
        "description": "A full day in Yala with a picnic, giving the best chance of leopard."
      },
      {
        "day": "Day 9",
        "title": "To Mirissa",
        "location": "Mirissa",
        "description": "Final dawn drive in Yala, then along the coast to Mirissa.",
        "drive": "3 hrs · 140 km"
      },
      {
        "day": "Day 10",
        "title": "Whales",
        "location": "Mirissa",
        "description": "Early boat to find blue whales and spinner dolphins (November to April)."
      },
      {
        "day": "Day 11",
        "title": "Departure",
        "location": "Airport",
        "description": "Transfer to the airport via the Southern Expressway.",
        "drive": "3 hrs · 180 km"
      }
    ],
    "inclusions": [
      "Private air-conditioned vehicle with an English-speaking chauffeur-guide",
      "Accommodation as listed (or similar) with daily breakfast",
      "Entrance fees for the sites and safaris named in the itinerary",
      "Highway tolls, fuel, and your chauffeur-guide's accommodation and meals",
      "Bottled water in the vehicle",
      "24/7 local support throughout your journey",
      "All jeep safaris with park fees and trackers",
      "Shared whale-watching boat"
    ],
    "exclusions": [
      "International flights and Sri Lanka visa / ETA fees",
      "Travel insurance (required for every booking)",
      "Meals not stated, drinks and personal expenses",
      "Gratuities for guides, drivers and hotel staff"
    ],
    "isActive": true
  }
] as Tour[];

export const DAY_TOURS: Tour[] = [
  {
    "id": "day-tour-yala",
    "title": "Yala National Park Safari",
    "category": "wildlife",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": "teal"
    },
    "image": "images/tours/day-tour-yala.jpg",
    "description": "An exclusive private 4x4 safari through Sri Lanka's premier wildlife sanctuary, accompanied by an experienced tracker.",
    "highlights": [
      "Private open-top jeep",
      "Leopard & elephant tracking",
      "Picnic refreshment setup"
    ],
    "startTime": "5:30 AM (Morning) or 2:00 PM (Afternoon)",
    "guests": "Private (1 – 6 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-sigiriya",
    "title": "Sigiriya Citadel & Dambulla Cave Temples",
    "category": "cultural",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": ""
    },
    "image": "images/tours/day-tour-sigiriya.jpg",
    "description": "Ascend the ancient 5th-century Lion Rock fortress and explore the painted cave sanctuaries of Dambulla in a single cultural loop.",
    "highlights": [
      "UNESCO Sigiriya Fortress",
      "Dambulla Cave Murals",
      "Traditional village lunch"
    ],
    "startTime": "7:00 AM",
    "guests": "Private (1 – 8 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-whale",
    "title": "Mirissa Ocean Whale Expedition",
    "category": "coast",
    "type": "day",
    "duration": "Half Day",
    "badge": {
      "text": "Half Day",
      "class": "teal"
    },
    "image": "images/tours/day-tour-whale.jpg",
    "description": "Set sail at dawn into the deep southern waters to observe migrating blue whales, sperm whales, and spinner dolphins.",
    "highlights": [
      "Blue whale & dolphin sightings",
      "Marine safety equipment",
      "Refreshments at sea"
    ],
    "startTime": "6:00 AM (Seasonal: Nov – Apr)",
    "guests": "2 – 8 Guests",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-kandy",
    "title": "Kandy Royal Heritage & Tea Trails",
    "category": "cultural",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": ""
    },
    "image": "images/tours/day-tour-kandy.jpg",
    "description": "Experience the sacred rituals of the Temple of the Tooth, wander the Royal Botanic Gardens, and explore a working mountain tea estate.",
    "highlights": [
      "Temple of the Sacred Tooth Relic",
      "Peradeniya Botanic Gardens",
      "Orthodox tea factory tour & tasting"
    ],
    "startTime": "8:00 AM",
    "guests": "Private (1 – 8 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-galle",
    "title": "Galle Fort & Southern Maritime Heritage",
    "category": "coast",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": ""
    },
    "image": "images/tours/day-tour-galle.jpg",
    "description": "Stroll the 17th-century ramparts of this living Dutch citadel, cruise the coastal mangrove lagoons, and visit a sea turtle sanctuary.",
    "highlights": [
      "UNESCO Galle Fort walking tour",
      "Madu Ganga river safari",
      "Marine turtle conservation project"
    ],
    "startTime": "8:30 AM",
    "guests": "Private (1 – 6 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-tea",
    "title": "Nuwara Eliya Highlands & High Tea",
    "category": "highlands",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": "teal"
    },
    "image": "images/tours/day-tour-tea.jpg",
    "description": "Journey into the misty tea country, walk through heritage rolling estates, and experience classic Ceylon high tea.",
    "highlights": [
      "Colonial architecture of 'Little England'",
      "Factory processing masterclass",
      "Fine highland tea tasting"
    ],
    "startTime": "7:30 AM",
    "guests": "Private (1 – 6 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-ella",
    "title": "Ella: Nine Arches & Little Adam's Peak",
    "category": "highlands",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": "teal"
    },
    "image": "images/destinations/ella.jpg",
    "description": "An easy hike to Little Adam's Peak for views across Ella Gap, then the Nine Arches Bridge as a train crosses.",
    "highlights": [
      "Little Adam's Peak",
      "Nine Arches Bridge",
      "Ravana Falls"
    ],
    "startTime": "7:00 AM",
    "guests": "Private (1 – 6 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-dambulla",
    "title": "Dambulla Cave Temples & Village Life",
    "category": "cultural",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": "teal"
    },
    "image": "images/destinations/dambulla.jpg",
    "description": "The painted cave temples of Dambulla, then a village afternoon with a bullock-cart ride and a home-cooked lunch.",
    "highlights": [
      "Dambulla cave temples",
      "Bullock-cart ride",
      "Village lunch"
    ],
    "startTime": "8:00 AM",
    "guests": "Private (1 – 6 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  },
  {
    "id": "day-tour-anuradhapura",
    "title": "Anuradhapura Sacred City",
    "category": "cultural",
    "type": "day",
    "duration": "Full Day",
    "badge": {
      "text": "Full Day",
      "class": "teal"
    },
    "image": "images/destinations/anuradhapura.jpg",
    "description": "By bicycle or vehicle through Sri Lanka's first great capital: vast stupas, the sacred Bodhi tree and ancient reservoirs.",
    "highlights": [
      "Ruwanwelisaya stupa",
      "Sri Maha Bodhi tree",
      "Cycling the ruins"
    ],
    "startTime": "7:30 AM",
    "guests": "Private (1 – 6 Guests)",
    "price": null,
    "pricingType": "bespoke",
    "priceType": "Bespoke Quote",
    "priceDisplay": "Tailor-made",
    "isActive": true
  }
] as Tour[];

export const DESTINATIONS: Destination[] = [
  {
    "name": "Sigiriya",
    "tagline": "The Ancient Citadel",
    "description": "Ascend the legendary Lion Rock fortress and explore the royal water gardens of this 5th-century architectural marvel.",
    "tags": [
      "History",
      "Photography",
      "Hiking"
    ],
    "region": "Cultural Triangle",
    "imageUrl": "assets/images/destinations/sigiriya.jpg",
    "isActive": true,
    "id": "dest-sigiriya"
  },
  {
    "name": "Anuradhapura",
    "tagline": "Sacred Ancient Wonders",
    "description": "Marvel at towering white stupas, the sacred Sri Maha Bodhi tree, and the sprawling ruins of Sri Lanka's first ancient kingdom.",
    "tags": [
      "Ancient Wonders",
      "Spirituality",
      "UNESCO Heritage"
    ],
    "region": "Cultural Triangle",
    "imageUrl": "assets/images/destinations/anuradhapura.jpg",
    "isActive": true,
    "id": "dest-anuradhapura"
  },
  {
    "name": "Dambulla",
    "tagline": "Golden Cave Temples",
    "description": "Discover centuries-old golden cave temple murals and hundreds of sacred Buddha statues carved directly into the rock face.",
    "tags": [
      "Culture",
      "Spirituality",
      "History"
    ],
    "region": "Cultural Triangle",
    "imageUrl": "assets/images/destinations/dambulla.jpg",
    "isActive": true,
    "id": "dest-dambulla"
  },
  {
    "name": "Ella",
    "tagline": "Emerald Peaks & Valleys",
    "description": "Journey through misty tea plantations, cross the iconic Nine Arches Bridge, and hike to breathtaking viewpoints above the clouds.",
    "tags": [
      "Nature",
      "Hiking",
      "Train Rides"
    ],
    "region": "Hill Country",
    "imageUrl": "assets/images/destinations/ella.jpg",
    "isActive": true,
    "id": "dest-ella"
  },
  {
    "name": "Mirissa",
    "tagline": "Golden Sands & Whales",
    "description": "Watch blue whales breach at sunrise, surf pristine waves, and dine on the freshest seafood at sunset on golden beaches.",
    "tags": [
      "Beach",
      "Whale Watching",
      "Surfing"
    ],
    "region": "South Coast",
    "imageUrl": "assets/images/destinations/mirissa.jpg",
    "isActive": true,
    "id": "dest-mirissa"
  },
  {
    "name": "Galle Fort",
    "tagline": "Colonial Charm",
    "description": "Wander the cobblestone streets of this UNESCO fortress, where Dutch colonial architecture meets Indian Ocean sunsets and boutique galleries.",
    "tags": [
      "History",
      "Shopping",
      "Architecture"
    ],
    "region": "South Coast",
    "imageUrl": "assets/images/destinations/galle.jpg",
    "isActive": true,
    "id": "dest-galle-fort"
  },
  {
    "name": "Yala National Park",
    "tagline": "Untamed Wilderness",
    "description": "Home to the highest density of leopards in the world, alongside elephants, sloth bears, and over 200 bird species in stunning landscapes.",
    "tags": [
      "Wildlife",
      "Photography",
      "Safari"
    ],
    "region": "South East",
    "imageUrl": "assets/images/destinations/yala.jpg",
    "isActive": true,
    "id": "dest-yala-national-park"
  },
  {
    "name": "Kandy",
    "tagline": "Sacred Hill Capital",
    "description": "Home to the Temple of the Tooth Relic and surrounded by lush hills, Kandy is the cultural heart of Sri Lanka — steeped in royal heritage.",
    "tags": [
      "Culture",
      "Temples",
      "Gardens"
    ],
    "region": "Hill Country",
    "imageUrl": "assets/images/destinations/kandy.jpg",
    "isActive": true,
    "id": "dest-kandy"
  },
  {
    "name": "Nuwara Eliya",
    "tagline": "Little England in the Hills",
    "description": "Stroll through emerald tea estates, visit historic colonial factories, and savor Ceylon high tea amidst mist-kissed hills.",
    "tags": [
      "Tea Tasting",
      "Cool Climate",
      "Colonial Heritage"
    ],
    "region": "Hill Country",
    "imageUrl": "assets/images/destinations/nuwara-eliya.jpg",
    "isActive": true,
    "id": "dest-nuwara-eliya"
  }
];
