"""
Builds the built-in tour/destination catalogue from data/*.json (the single source of truth):
  - frontend/src/app/data/catalog.ts   (shown when the API is unreachable)
  - backend/catalog_data.py            (seeds an empty database / serves when MongoDB is down)
  - frontend/public/sitemap.xml        (every public page, tour and journal article)

Run after editing any data/*.json file:
    python data/build_catalog.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load(name):
    with open(os.path.join(HERE, name), encoding='utf8') as f:
        data = json.load(f)
    return data if isinstance(data, list) else list(data.values())[0]


def slug(text):
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')


def clean_tour(t):
    t = dict(t)
    t.pop('link', None)
    t.pop('durationLabel', None)
    t.setdefault('isActive', True)
    return t


round_tours = [clean_tour(t) for t in load('tours-uk.json')]
day_tours = [clean_tour(t) for t in load('day-tours-uk.json')]
destinations = []
for d in load('destinations.json'):
    d = dict(d)
    d.setdefault('id', 'dest-' + slug(d['name']))
    destinations.append(d)

ts = f"""/**
 * Built-in copy of the tour and destination catalogue.
 * GENERATED by data/build_catalog.py from data/*.json. Do not edit by hand.
 */
import {{ Tour }} from '../services/tour.service';
import {{ Destination }} from '../services/destination.service';

export const ROUND_TOURS: Tour[] = {json.dumps(round_tours, indent=2, ensure_ascii=False)} as Tour[];

export const DAY_TOURS: Tour[] = {json.dumps(day_tours, indent=2, ensure_ascii=False)} as Tour[];

export const DESTINATIONS: Destination[] = {json.dumps(destinations, indent=2, ensure_ascii=False)};
"""
with open(os.path.join(ROOT, 'frontend', 'src', 'app', 'data', 'catalog.ts'), 'w', encoding='utf8') as f:
    f.write(ts)

py = f'''"""
Built-in tour and destination catalogue.
GENERATED by data/build_catalog.py from data/*.json. Do not edit by hand.
"""
import json

CATALOG_TOURS = json.loads({json.dumps(json.dumps(round_tours + day_tours, ensure_ascii=False), ensure_ascii=False)})

CATALOG_DESTINATIONS = json.loads({json.dumps(json.dumps(destinations, ensure_ascii=False), ensure_ascii=False)})
'''
with open(os.path.join(ROOT, 'backend', 'catalog_data.py'), 'w', encoding='utf8') as f:
    f.write(py)

# ── Sitemap ──
journal_ts = open(os.path.join(ROOT, 'frontend', 'src', 'app', 'data', 'journal.ts'), encoding='utf8').read()
articles = re.findall(r"slug: '([^']+)'", journal_ts)
pages = ['', 'round-tours', 'day-tours', 'destinations', 'experiences', 'tailor-made', 'about', 'journal', 'contact',
         'privacy', 'terms-and-conditions']
pages += [f"tours/{t['id']}" for t in round_tours + day_tours if t.get('isActive', True)]
pages += [f'journal/{slug}' for slug in articles]
urls = ''.join(f'  <url><loc>https://zeilanparadise.com/{p}</loc></url>\n' for p in pages)
with open(os.path.join(ROOT, 'frontend', 'public', 'sitemap.xml'), 'w', encoding='utf8') as f:
    f.write('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls + '</urlset>\n')

print(f'{len(pages)} sitemap URLs')
print(f'{len(round_tours)} round tours, {len(day_tours)} day tours, {len(destinations)} destinations')
